#ifndef PROGRESSTYPE_H
#define PROGRESSTYPE_H

typedef enum {
	PLAINTEXT_TO_ARCHIVE,
	ARCHIVE_TO_CIPHERTEXT,
	CIPHERTEXT_TO_ARCHIVE,
	ARCHIVE_TO_PLAINTEXT,
	ENCRYPTION_MOVING_FILE,
	DECRYPTION_MOVING_FILE
} ProgressType;


#endif // PROGRESSTYPE_H
